// Generated by CoffeeScript 1.6.2
(function() {
  var n, square;

  square = function(x) {
    return x * x;
  };

  n = 4;

  console.log("" + n + " squared is " + (square(n)));

  if (foo) {
    foo.onload = function() {
      return console.log('Hello from CoffeeScript!');
    };
  }

}).call(this);
